# Makefile to compile numberconversion program

# Compiler
CC=g++

# Compiler flags
CFLAGS=-Wall

# Executable name
EXEC=romandigitconverter

# Default target
all: $(EXEC)

# Compile the main executable
$(EXEC): romandigitconverter.o numberconversion.o
	$(CC) $(CFLAGS) -o $(EXEC) romandigitconverter.o numberconversion.o

# Compile romandigitconverter.cpp to an object file
romandigitconverter.o: romandigitconverter.cpp numberconversion.h
	$(CC) $(CFLAGS) -c romandigitconverter.cpp

# Compile numberconversion.cpp to an object file
numberconversion.o: numberconversion.cpp numberconversion.h
	$(CC) $(CFLAGS) -c numberconversion.cpp

# Clean target
clean:
	rm -f *.o $(EXEC)
